"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleAlert, CircleCheck, Link2, Pencil, Plus, Trash2, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { ChapterService } from "@/services/chapter.service";
import { ItemService } from "@/services/item.service";
import type { BudgetChapter, BudgetItem } from "@/types/budget";

export default function ProjectApuOverview({projectId}:{projectId:string}) {
 const [items,setItems]=useState<BudgetItem[]>([]); const [chapters,setChapters]=useState<BudgetChapter[]>([]);
 const [targets,setTargets]=useState<Record<string,string>>({});
 const [editing,setEditing]=useState<BudgetItem | null>(null);
 const refresh=()=>{setItems(ItemService.findByProject(projectId));setChapters(ChapterService.findByProject(projectId));};
 useEffect(()=>{refresh();},[projectId]);
 const map=useMemo(()=>new Map(chapters.map(c=>[c.id,c])),[chapters]);
 const priced=items.filter(i=>i.status==="priced").length; const pending=items.length-priced;
 const orphaned=items.filter(i=>!map.has(i.chapterId)).length;
 const reassign=(itemId:string)=>{const chapterId=targets[itemId]; if(!chapterId)return; ItemService.update(itemId,{chapterId}); refresh();};
 const remove=(item:BudgetItem)=>{if(!window.confirm(`¿Eliminar la partida ${item.code ? item.code+" · " : ""}${item.name}? También se eliminarán sus recursos APU.`))return; ItemService.delete(item.id); refresh();};
 const saveEdit=()=>{if(!editing)return; ItemService.update(editing.id,{code:editing.code,name:editing.name,unit:editing.unit,quantity:editing.quantity,chapterId:editing.chapterId}); setEditing(null); refresh();};
 return <main className="min-h-screen bg-slate-100 p-6 lg:p-10 text-slate-950"><div className="mx-auto max-w-6xl">
 <Link href={`/projects/${projectId}`} className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-blue-600"><ArrowLeft className="h-4 w-4"/>Proyecto</Link>
 <div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">Paso 4</p><h1 className="text-3xl font-bold">Centro de análisis de precios</h1><p className="mt-2 text-slate-500">Controla, edita y completa las partidas y sus APU.</p></div><Link href={`/projects/${projectId}/chapters`} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><Plus className="h-4 w-4"/>Agregar partida</Link></div>
 <div className="mt-7 grid gap-4 sm:grid-cols-4"><Stat label="Total partidas" value={items.length}/><Stat label="APU valorizados" value={priced}/><Stat label="Pendientes" value={pending}/><Stat label="Sin capítulo" value={orphaned}/></div>
 {orphaned>0&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Hay {orphaned} partida{orphaned===1?"":"s"} sin capítulo válido.</strong> Esto ocurre cuando una partida conserva la referencia a un capítulo que ya no existe. Reubícala abajo antes de abrir su APU.</div>}
 <section className="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{items.length===0?<div className="p-10 text-center text-slate-500">Primero agrega partidas al proyecto.</div>:items.map(i=>{const chapter=map.get(i.chapterId); const isOrphan=!chapter; return <div key={i.id} className="flex flex-col gap-3 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3">{isOrphan?<CircleAlert className="mt-0.5 h-5 w-5 text-red-500"/>:i.status==="priced"?<CircleCheck className="mt-0.5 h-5 w-5 text-emerald-500"/>:<CircleAlert className="mt-0.5 h-5 w-5 text-amber-500"/>}<div><strong>{i.code ? `${i.code} · ` : ""}{i.name}</strong><p className="mt-1 text-sm text-slate-500">{chapter?.name ?? "Sin capítulo"} · {i.status==="priced"?`RD$ ${i.unitPrice.toLocaleString("es-DO",{minimumFractionDigits:2})}/${i.unit}`:"APU pendiente"}</p></div></div>{isOrphan?<div className="flex flex-wrap items-center gap-2"><select value={targets[i.id]??""} onChange={e=>setTargets(v=>({...v,[i.id]:e.target.value}))} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">Asignar capítulo…</option>{chapters.map(c=><option key={c.id} value={c.id}>{c.code?`${c.code} · `:""}{c.name}</option>)}</select><button onClick={()=>reassign(i.id)} disabled={!targets[i.id]} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><Link2 className="h-4 w-4"/>Reubicar</button></div>:<div className="flex flex-wrap items-center gap-2"><button onClick={()=>setEditing(i)} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600 hover:text-blue-600"><Pencil className="h-4 w-4"/>Editar</button><button onClick={()=>remove(i)} className="inline-flex items-center gap-1 rounded-lg border border-red-100 px-3 py-2 text-sm font-semibold text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/>Eliminar</button><Link href={`/projects/${projectId}/chapters/${i.chapterId}/items/${i.id}`} className="inline-flex items-center gap-2 rounded-lg px-3 py-2 font-semibold text-blue-600">{i.status==="priced"?"Revisar APU":"Analizar"}<ArrowRight className="h-4 w-4"/></Link></div>}</div>})}</section>
 {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Editar partida</h2><button onClick={()=>setEditing(null)}><X className="h-5 w-5"/></button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm">Código<input value={editing.code??""} onChange={e=>setEditing({...editing,code:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm">Capítulo<select value={editing.chapterId} onChange={e=>setEditing({...editing,chapterId:e.target.value})} className="mt-1 w-full rounded-xl border p-3">{chapters.map(c=><option key={c.id} value={c.id}>{c.code?`${c.code} · `:""}{c.name}</option>)}</select></label><label className="text-sm sm:col-span-2">Descripción<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm">Cantidad<input type="number" value={editing.quantity} onChange={e=>setEditing({...editing,quantity:Number(e.target.value)})} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm">Unidad<input value={editing.unit} onChange={e=>setEditing({...editing,unit:e.target.value})} className="mt-1 w-full rounded-xl border p-3"/></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setEditing(null)} className="rounded-xl border px-4 py-2">Cancelar</button><button onClick={saveEdit} className="rounded-xl bg-blue-600 px-5 py-2 font-semibold text-white">Guardar cambios</button></div></div></div>}
 </div></main>;
}
function Stat({label,value}:{label:string;value:number}) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>; }
