"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { ProjectReviewService } from "@/services/projectReview.service";
import { ProjectService } from "@/services/project.service";
import type { ProjectReviewResult } from "@/types/projectReview";

export default function ProjectReviewWorkspace({projectId}:{projectId:string}){
 const [review,setReview]=useState<ProjectReviewResult|null>(null); const project=ProjectService.findById(projectId);
 const run=()=>setReview(ProjectReviewService.run(projectId)); useEffect(()=>run(),[projectId]);
 if(!project||!review)return <main className="min-h-screen bg-slate-100 p-10 text-slate-500">Preparando revisión...</main>;
 const ready=review.critical===0;
 return <main className="min-h-screen bg-slate-100 p-6 text-slate-950 lg:p-10"><div className="mx-auto max-w-6xl">
  <Link href={`/projects/${projectId}`} className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-blue-600"><ArrowLeft className="h-4 w-4"/>Proyecto</Link>
  <div className="mt-5 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-blue-600"><ShieldCheck className="h-4 w-4"/>Control de calidad</div><h1 className="mt-1 text-3xl font-black">Revisión del presupuesto</h1><p className="mt-2 text-slate-500">NEXUS valida integridad, precios, APU y trazabilidad antes de emitir.</p></div><button onClick={run} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 font-semibold"><RefreshCw className="h-4 w-4"/>Volver a revisar</button></div>
  <section className={`mt-7 rounded-3xl border p-7 ${ready?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-600">Preparación del proyecto</p><p className="mt-1 text-5xl font-black">{review.score}%</p><p className="mt-2 text-sm text-slate-600">{ready?"Sin bloqueos críticos. Puedes continuar a la emisión final.":"Hay observaciones críticas que conviene resolver antes de emitir."}</p></div><div className="grid grid-cols-3 gap-3"><Metric label="Críticos" value={review.critical} tone="red"/><Metric label="Revisar" value={review.warnings} tone="amber"/><Metric label="Superadas" value={review.passed} tone="green"/></div></div></section>
  <div className="mt-7 space-y-3">{review.issues.length===0?<div className="rounded-3xl border border-emerald-200 bg-white p-10 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500"/><h2 className="mt-4 text-xl font-bold">Proyecto validado</h2><p className="mt-2 text-slate-500">No detectamos observaciones pendientes en las reglas actuales.</p></div>:review.issues.map(issue=><article key={issue.id} className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3">{issue.severity==="critical"?<CircleAlert className="mt-0.5 h-5 w-5 text-red-500"/>:<TriangleAlert className="mt-0.5 h-5 w-5 text-amber-500"/>}<div><div className="flex flex-wrap items-center gap-2"><strong>{issue.title}</strong><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${issue.severity==="critical"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{issue.severity==="critical"?"Crítico":"Revisar"}</span></div><p className="mt-1 text-sm text-slate-500">{issue.detail}</p></div></div>{issue.href&&<Link href={issue.href} className="inline-flex items-center gap-2 self-start rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Corregir<ArrowRight className="h-4 w-4"/></Link>}</article>)}</div>
  <div className="mt-7 flex justify-end"><Link href={`/projects/${projectId}/budget`} className={`inline-flex items-center gap-2 rounded-xl px-5 py-3 font-semibold ${ready?"bg-blue-600 text-white":"border border-slate-300 bg-white text-slate-500"}`}>Ir al presupuesto<ArrowRight className="h-4 w-4"/></Link></div>
 </div></main>
}
function Metric({label,value,tone}:{label:string;value:number;tone:"red"|"amber"|"green"}){const cls={red:"bg-red-100 text-red-800",amber:"bg-amber-100 text-amber-800",green:"bg-emerald-100 text-emerald-800"}[tone];return <div className={`min-w-24 rounded-2xl p-4 text-center ${cls}`}><p className="text-2xl font-black">{value}</p><p className="text-xs font-semibold">{label}</p></div>}
