import { LocalStorageRepository } from "@/repositories/localStorage.repository";
import { BudgetService } from "@/services/budget.service";
import { ItemService } from "@/services/item.service";
import type { BudgetRevision, RevisionItemChange } from "@/types/revision";
import { SettingsService } from "@/services/settings.service";
const KEY="nexus-budget-revisions";
export class RevisionService {
 static findByProject(projectId:string):BudgetRevision[]{return (LocalStorageRepository.get<BudgetRevision[]>(KEY)??[]).filter(r=>r.projectId===projectId).sort((a,b)=>b.number-a.number)}
 static create(projectId:string,note=""):BudgetRevision|null{const budget=BudgetService.findOrCreateByProject(projectId);const items=ItemService.findByProject(projectId);const directCost=items.reduce((s,i)=>s+(i.unitPrice||0)*(i.quantity||0),0);const a=budget.adjustments;const ge=directCost*a.generalExpensesPercentage/100;const co=(directCost+ge)*a.contingencyPercentage/100;const pr=(directCost+ge+co)*a.profitPercentage/100;const total=(directCost+ge+co+pr)*(1+a.itbisPercentage/100);const current=this.findByProject(projectId);const number=(current[0]?.number??-1)+1;const year=new Date().getFullYear();const prefix=SettingsService.get().documentPrefix||"NX-PRE";const revision:BudgetRevision={id:`REV-${projectId}-${Date.now()}`,projectId,number,label:`Rev. ${number}`,documentCode:`${prefix}-${year}-${projectId.replace(/\D/g,"").slice(-4).padStart(4,"0")}-R${number}`,directCost,total,itemsCount:items.length,pricedItemsCount:items.filter(i=>i.status==="priced").length,note:note.trim(),createdAt:new Date().toISOString(),items:items.map(i=>({id:i.id,code:i.code,name:i.name,unit:i.unit,quantity:i.quantity,unitPrice:i.unitPrice||0,amount:(i.unitPrice||0)*i.quantity}))};LocalStorageRepository.save(KEY,[revision,...(LocalStorageRepository.get<BudgetRevision[]>(KEY)??[])]);return revision}
 static compare(current:BudgetRevision,previous:BudgetRevision):RevisionItemChange[]{const key=(x:{code?:string;name:string})=>(x.code?.trim().toLowerCase()||x.name.trim().toLowerCase());const a=new Map((previous.items??[]).map(x=>[key(x),x]));const b=new Map((current.items??[]).map(x=>[key(x),x]));const out:RevisionItemChange[]=[];new Set([...a.keys(),...b.keys()]).forEach(k=>{const p=a.get(k),c=b.get(k);if(!p&&c)out.push({key:k,kind:"added",name:c.name,code:c.code,currentQuantity:c.quantity,currentUnitPrice:c.unitPrice,currentAmount:c.amount});else if(p&&!c)out.push({key:k,kind:"removed",name:p.name,code:p.code,previousQuantity:p.quantity,previousUnitPrice:p.unitPrice,previousAmount:p.amount});else if(p&&c&&(p.quantity!==c.quantity||p.unitPrice!==c.unitPrice||p.amount!==c.amount))out.push({key:k,kind:"changed",name:c.name,code:c.code,previousQuantity:p.quantity,currentQuantity:c.quantity,previousUnitPrice:p.unitPrice,currentUnitPrice:c.unitPrice,previousAmount:p.amount,currentAmount:c.amount})});return out}
}
