"use client";
import { Building2, CheckCircle2, FileText, Palette, Save, Settings2, Upload, X } from "lucide-react";
import { useEffect, useState } from "react";
import { SettingsService } from "@/services/settings.service";
import type { BudgetTemplate, CompanySettings, NexusAppTheme } from "@/types/settings";
import { useToast } from "@/components/ui/ToastProvider";
import { applyNexusTheme } from "@/components/settings/ThemeApplier";

const themes:{id:NexusAppTheme;name:string;colors:string[]}[]=[
 {id:"nexus-blue",name:"NEXUS Blue",colors:["#2563eb","#38bdf8"]},{id:"executive-navy",name:"Executive Navy",colors:["#1e3a8a","#c59d5f"]},{id:"engineering-slate",name:"Engineering Slate",colors:["#475569","#0ea5e9"]},{id:"emerald",name:"Emerald",colors:["#059669","#34d399"]},{id:"graphite",name:"Graphite",colors:["#3f3f46","#a1a1aa"]},{id:"corporate-light",name:"Corporate Light",colors:["#1d4ed8","#64748b"]},{id:"custom",name:"Personalizado",colors:["#111827","#d1d5db"]},
];
const templates:{id:BudgetTemplate;name:string;desc:string}[]=[
 {id:"corporate",name:"Corporate",desc:"Formal, institucional y equilibrada."},{id:"executive",name:"Executive",desc:"Minimalista, elegante y con mucho espacio."},{id:"engineering",name:"Engineering",desc:"Técnica, compacta y centrada en tablas."},{id:"modern",name:"Modern",desc:"Bloques gráficos y total protagonista."},{id:"classic",name:"Classic",desc:"Cotización tradicional y conservadora."},
];
export default function SettingsWorkspace(){
 const [value,setValue]=useState<CompanySettings|null>(null); const [saved,setSaved]=useState(false); const {notify}=useToast();
 useEffect(()=>setValue(SettingsService.get()),[]); if(!value)return <main className="min-h-screen bg-slate-100 p-10 text-slate-500">Cargando configuración...</main>;
 const set=<K extends keyof CompanySettings>(key:K,v:CompanySettings[K])=>{setValue({...value,[key]:v});setSaved(false)};
 const save=()=>{const next=SettingsService.save(value);setValue(next);setSaved(true);window.dispatchEvent(new Event("nexus-settings-changed"));applyNexusTheme();notify("Configuración guardada","Identidad, tema y plantillas actualizados.");window.setTimeout(()=>setSaved(false),2500)};
 const image=(key:"logoDataUrl"|"darkLogoDataUrl")=>(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>set(key,String(r.result||""));r.readAsDataURL(f)};
 return <main className="min-h-screen bg-slate-100 p-6 text-slate-950 lg:p-10"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-600">Configuración</p><h1 className="mt-1 text-3xl font-black">Identidad, apariencia y documentos</h1><p className="mt-2 text-slate-500">Personaliza cómo trabaja tu equipo y cómo tus clientes ven cada propuesta.</p></div><button onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white shadow-lg"><Save className="h-4 w-4"/>Guardar configuración</button></div>
  {saved&&<div className="mt-5 flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>Configuración guardada.</div>}
  <div className="mt-7 grid gap-6 lg:grid-cols-2">
   <Card icon={Building2} title="Identidad corporativa"><LogoInput label="Logo principal" value={value.logoDataUrl} onChange={image("logoDataUrl")} onClear={()=>set("logoDataUrl","")}/><LogoInput label="Logo alternativo (fondos oscuros)" value={value.darkLogoDataUrl} dark onChange={image("darkLogoDataUrl")} onClear={()=>set("darkLogoDataUrl","")}/><Field label="Nombre comercial" value={value.commercialName} onChange={v=>set("commercialName",v)}/><Field label="Razón social" value={value.legalName} onChange={v=>set("legalName",v)}/><div className="grid gap-4 sm:grid-cols-2"><Field label="RNC" value={value.taxId} onChange={v=>set("taxId",v)}/><Field label="Teléfono" value={value.phone} onChange={v=>set("phone",v)}/></div><Field label="Correo" value={value.email} onChange={v=>set("email",v)}/><Field label="Dirección" value={value.address} onChange={v=>set("address",v)}/></Card>
   <Card icon={Palette} title="Apariencia de NEXUS"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{themes.map(t=><button type="button" key={t.id} onClick={()=>set("appTheme",t.id)} className={`rounded-2xl border p-3 text-left ${value.appTheme===t.id?"border-blue-600 ring-2 ring-blue-100":"border-slate-200"}`}><div className="mb-2 flex gap-1">{t.colors.map(c=><span key={c} className="h-5 w-5 rounded-full border border-black/10" style={{background:c}}/>)}</div><span className="text-xs font-bold">{t.name}</span></button>)}</div><label className="block text-sm font-medium text-slate-700">Modo<select value={value.appAppearance} onChange={e=>set("appAppearance",e.target.value as CompanySettings["appAppearance"])} className="mt-1 w-full rounded-xl border border-slate-200 bg-white p-3"><option value="light">Claro</option><option value="dark">Oscuro</option></select></label>{value.appTheme==="custom"&&<div className="grid grid-cols-2 gap-4"><ColorField label="Principal" value={value.customPrimaryColor} onChange={v=>set("customPrimaryColor",v)}/><ColorField label="Acento" value={value.customAccentColor} onChange={v=>set("customAccentColor",v)}/></div>}<p className="text-xs leading-5 text-slate-500">Los colores de validación (éxito, advertencia y error) conservan su significado.</p></Card>
   <Card icon={FileText} title="Plantilla del presupuesto"><div className="grid gap-3 sm:grid-cols-2">{templates.map(t=><button type="button" key={t.id} onClick={()=>set("budgetTemplate",t.id)} className={`overflow-hidden rounded-2xl border text-left ${value.budgetTemplate===t.id?"border-blue-600 ring-2 ring-blue-100":"border-slate-200"}`}><TemplateThumb kind={t.id} primary={value.documentPrimaryColor}/><div className="p-3"><p className="font-bold">{t.name}</p><p className="mt-1 text-xs text-slate-500">{t.desc}</p></div></button>)}</div><div className="grid grid-cols-3 gap-3"><ColorField label="Primario" value={value.documentPrimaryColor} onChange={v=>set("documentPrimaryColor",v)}/><ColorField label="Secundario" value={value.documentSecondaryColor} onChange={v=>set("documentSecondaryColor",v)}/><ColorField label="Acento" value={value.documentAccentColor} onChange={v=>set("documentAccentColor",v)}/></div><p className="text-xs text-slate-500">La plantilla documental es independiente del tema con el que usas NEXUS.</p></Card>
   <Card icon={Settings2} title="Contenido del documento"><div className="grid gap-2 sm:grid-cols-2"><Toggle label="Portada" checked={value.documentShowCover} onChange={v=>set("documentShowCover",v)}/><Toggle label="Logo" checked={value.documentShowLogo} onChange={v=>set("documentShowLogo",v)}/><Toggle label="Contacto empresa" checked={value.documentShowCompanyContact} onChange={v=>set("documentShowCompanyContact",v)}/><Toggle label="Datos completos cliente" checked={value.documentShowClientDetails} onChange={v=>set("documentShowClientDetails",v)}/><Toggle label="Cantidades" checked={value.documentShowQuantities} onChange={v=>set("documentShowQuantities",v)}/><Toggle label="Precios unitarios" checked={value.documentShowUnitPrices} onChange={v=>set("documentShowUnitPrices",v)}/><Toggle label="Desglose impuestos" checked={value.documentShowTaxBreakdown} onChange={v=>set("documentShowTaxBreakdown",v)}/><Toggle label="Subtotales capítulos" checked={value.documentShowChapterSubtotals} onChange={v=>set("documentShowChapterSubtotals",v)}/><Toggle label="Aceptación / firmas" checked={value.documentShowAcceptance} onChange={v=>set("documentShowAcceptance",v)}/></div></Card>
   <Card icon={Settings2} title="Reglas de presupuesto"><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Gastos generales %" value={value.defaultGeneralExpensesPercentage} onChange={v=>set("defaultGeneralExpensesPercentage",v)}/><NumberField label="Imprevistos %" value={value.defaultContingencyPercentage} onChange={v=>set("defaultContingencyPercentage",v)}/><NumberField label="Beneficio %" value={value.defaultProfitPercentage} onChange={v=>set("defaultProfitPercentage",v)}/><NumberField label="ITBIS %" value={value.defaultTaxPercentage} onChange={v=>set("defaultTaxPercentage",v)}/></div><NumberField label="Vigencia predeterminada (días)" value={value.defaultValidityDays} onChange={v=>set("defaultValidityDays",v)}/><Field label="Prefijo de presupuesto" value={value.documentPrefix} onChange={v=>set("documentPrefix",v.toUpperCase().replace(/[^A-Z0-9-]/g,""))}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Responsable" value={value.responsibleName} onChange={v=>set("responsibleName",v)}/><Field label="Cargo" value={value.responsibleTitle} onChange={v=>set("responsibleTitle",v)}/></div><label className="block text-sm font-medium text-slate-700">Notas predeterminadas<textarea rows={4} value={value.defaultNotes} onChange={e=>set("defaultNotes",e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label></Card>
   <DocumentPreview value={value}/>
  </div>
 </div></main>
}
function Card({icon:Icon,title,children}:{icon:React.ComponentType<{className?:string}>;title:string;children:React.ReactNode}){return <section className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="mb-6 flex items-center gap-3"><span className="rounded-xl bg-blue-50 p-2 text-blue-600"><Icon className="h-5 w-5"/></span><h2 className="text-xl font-bold">{title}</h2></div><div className="space-y-4">{children}</div></section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-medium text-slate-700">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-blue-400"/></label>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="block text-sm font-medium text-slate-700">{label}<input type="number" min="0" value={value} onChange={e=>onChange(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-blue-400"/></label>}
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs font-medium text-slate-600">{label}<div className="mt-1 flex items-center gap-2 rounded-xl border border-slate-200 p-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-8 w-9 cursor-pointer border-0 bg-transparent"/><span className="truncate text-xs uppercase">{value}</span></div></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm font-medium text-slate-700"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-blue-600"/></label>}
function LogoInput({label,value,dark,onChange,onClear}:{label:string;value?:string;dark?:boolean;onChange:(e:React.ChangeEvent<HTMLInputElement>)=>void;onClear:()=>void}){return <div><label className="block text-sm font-medium text-slate-700">{label}<span className="mt-1 flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-2 text-sm"><Upload className="h-4 w-4"/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={onChange} className="min-w-0 flex-1"/></span></label>{value&&<div className={`relative mt-2 rounded-2xl border p-3 ${dark?"bg-slate-950":"bg-white"}`}><img src={value} alt={label} className="max-h-16 max-w-[200px] object-contain"/><button type="button" onClick={onClear} className="absolute right-2 top-2 rounded-lg bg-white p-1 text-slate-700 shadow"><X className="h-4 w-4"/></button></div>}</div>}
function TemplateThumb({kind,primary}:{kind:BudgetTemplate;primary:string}){return <div className="h-24 bg-slate-50 p-3"><div className={`h-full overflow-hidden rounded border bg-white ${kind==="classic"?"p-2":""}`}><div className="h-5" style={{background:kind==="executive"?"white":primary}}/><div className="space-y-1 p-2"><div className="h-1.5 w-1/2 rounded bg-slate-300"/><div className="h-1.5 w-3/4 rounded bg-slate-200"/><div className={`mt-2 h-4 rounded ${kind==="modern"?"w-2/3":"w-full"}`} style={{background:`${primary}22`}}/></div></div></div>}
function DocumentPreview({value}:{value:CompanySettings}){return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="p-5 text-white" style={{background:value.documentSecondaryColor}}><p className="text-[10px] font-bold uppercase tracking-[.2em]" style={{color:value.documentAccentColor}}>Vista previa · {value.budgetTemplate}</p><div className="mt-4 flex items-center gap-4">{value.documentShowLogo&&value.logoDataUrl&&<img src={value.darkLogoDataUrl||value.logoDataUrl} alt="Logo" className="max-h-12 max-w-28 object-contain"/>}<div><h2 className="text-xl font-black">{value.commercialName||"Tu empresa"}</h2><p className="text-xs text-white/70">PROPUESTA ECONÓMICA</p></div></div></div><div className="p-6"><p className="text-xs font-bold" style={{color:value.documentPrimaryColor}}>PROYECTO</p><h3 className="mt-1 text-xl font-black">Residencial de ejemplo</h3><p className="mt-1 text-sm text-slate-500">Preparada para: Cliente de ejemplo</p><div className="mt-5 rounded-2xl p-4" style={{background:`${value.documentPrimaryColor}12`}}><p className="text-[10px] font-bold" style={{color:value.documentPrimaryColor}}>VALOR TOTAL</p><p className="mt-1 text-2xl font-black">RD$ 1,429,877.68</p></div><div className="mt-5 space-y-2"><div className="h-2 rounded bg-slate-100"/><div className="h-2 w-5/6 rounded bg-slate-100"/><div className="h-2 w-2/3 rounded bg-slate-100"/></div></div></section>}
